@echo off
echo Starting AI Video Assistant Backend (FastAPI + MongoDB)...
echo Activating virtual environment and starting server...
cd /d "%~dp0"
..\.venv\Scripts\python.exe -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
pause
